CREATE DATABASE IF NOT EXISTS Account;
CREATE TABLE IF NOT EXISTS Account.Registry
(
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    USERNAME CHAR(30) NOT NULL , 
    PASSWORD CHAR(30) NOT NULL , 
    MMORPG CHAR(61) DEFAULT NULL
);

ALTER TABLE Account.Registry AUTO_INCREMENT = 1;


CREATE DATABASE IF NOT EXISTS Servers;
CREATE TABLE IF NOT EXISTS Servers.Registry
(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY , 
	TYPE INT UNSIGNED NOT NULL , 
	IP CHAR(126) DEFAULT NULL , 
	PORT INT UNSIGNED DEFAULT 0 ,
	TCP INT DEFAULT 0 , 
	NAME CHAR(49) DEFAULT NULL , 
	TOKEN CHAR(62) DEFAULT NULL 
);

ALTER TABLE Servers.Registry AUTO_INCREMENT = 1;


CREATE DATABASE IF NOT EXISTS GameDatabases;
CREATE TABLE IF NOT EXISTS GameDatabases.Registry
(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY , 
	SERVER_ID INT UNSIGNED NOT NULL , 
	IP CHAR(126) NOT NULL ,
	PORT INT UNSIGNED NOT NULL , 
	USERNAME CHAR(126) , 
	PASSWORD CHAR(126) , 
	DATABASE_NAME CHAR(126)
);

ALTER TABLE GameDatabases.Registry AUTO_INCREMENT = 1;


CREATE DATABASE IF NOT EXISTS World_1;
CREATE TABLE IF NOT EXISTS World_1.Registry
(
	ACCOUNT INT UNSIGNED NOT NULL , 
	ID INT UNSIGNED NOT NULL , 
	NAME CHAR(61) NOT NULL UNIQUE , 
	LOGGED_IN INT UNSIGNED DEFAULT 0 , 
	ZONE INT UNSIGNED DEFAULT 0, 
	X DOUBLE DEFAULT 0 , 
	Y DOUBLE DEFAULT 0 , 
	Z DOUBLE DEFAULT 0 , 
	FACING_ANGLE INT UNSIGNED DEFAULT 0 , 
	INSTANCE_ZONE INT UNSIGNED DEFAULT 0 , 
	INSTANCE_X DOUBLE DEFAULT 0 , 
	INSTANCE_Y DOUBLE DEFAULT 0 , 
	INSTANCE_Z DOUBLE DEFAULT 0 , 
	INSTANCE_FACING_ANGLE INT UNSIGNED DEFAULT 0 , 
	HIT_POINTS INT UNSIGNED DEFAULT 0 , 
	PRIMARY KEY (ACCOUNT,ID)
);