CREATE USER 'writer'@'%' IDENTIFIED BY 'writerpass';
GRANT ALL PRIVILEGES ON *.* TO 'writer'@'%';
CREATE USER 'writer'@'localhost' IDENTIFIED BY 'writerpass';
GRANT ALL PRIVILEGES ON *.* TO 'writer'@'localhost';

CREATE USER 'reader'@'%' IDENTIFIED BY 'readerpass';
GRANT SELECT ON *.* TO 'reader'@'%';
CREATE USER 'reader'@'localhost' IDENTIFIED BY 'readerpass';
GRANT SELECT ON *.* TO 'reader'@'localhost';
FLUSH PRIVILEGES;


INSERT INTO Account.Registry (ID,USERNAME,PASSWORD,MMORPG) VALUES(1,'TestUser','TestPassword',NULL);

INSERT INTO GameDatabases.Registry (ID,SERVER_ID,IP,PORT,USERNAME,PASSWORD,DATABASE_NAME) VALUES(1,1,'120.0.0.1',3306,'writer','writerpass','Account');
INSERT INTO GameDatabases.Registry (ID,SERVER_ID,IP,PORT,USERNAME,PASSWORD,DATABASE_NAME) VALUES(2,1,'120.0.0.1',3306,'reader','readerpass','Account');
INSERT INTO GameDatabases.Registry (ID,SERVER_ID,IP,PORT,USERNAME,PASSWORD,DATABASE_NAME) VALUES(3,2,'120.0.0.1',3306,'writer','writerpass','Servers');
INSERT INTO GameDatabases.Registry (ID,SERVER_ID,IP,PORT,USERNAME,PASSWORD,DATABASE_NAME) VALUES(4,2,'120.0.0.1',3306,'reader','readerpass','Servers');
INSERT INTO GameDatabases.Registry (ID,SERVER_ID,IP,PORT,USERNAME,PASSWORD,DATABASE_NAME) VALUES(5,3,'120.0.0.1',3306,'writer','writerpass','World_1');
INSERT INTO GameDatabases.Registry (ID,SERVER_ID,IP,PORT,USERNAME,PASSWORD,DATABASE_NAME) VALUES(6,3,'120.0.0.1',3306,'reader','readerpass','World_1');

INSERT INTO Servers.Registry (ID,TYPE,IP,PORT,TCP,NAME,TOKEN) VALUES(1,1,'120.0.0.1',9171,1,'Login',NULL);
INSERT INTO Servers.Registry (ID,TYPE,IP,PORT,TCP,NAME,TOKEN) VALUES(2,2,'120.0.0.1',9172,1,'Shard List',NULL);
INSERT INTO Servers.Registry (ID,TYPE,IP,PORT,TCP,NAME,TOKEN) VALUES(3,3,'120.0.0.1',9173,1,'Shard Manager 1',NULL);
INSERT INTO Servers.Registry (ID,TYPE,IP,PORT,TCP,NAME,TOKEN) VALUES(4,4,'120.0.0.1',9174,1,'Chat 1',NULL);
INSERT INTO Servers.Registry (ID,TYPE,IP,PORT,TCP,NAME,TOKEN) VALUES(5,5,'120.0.0.1',9175,1,'World 1 1',NULL);
INSERT INTO Servers.Registry (ID,TYPE,IP,PORT,TCP,NAME,TOKEN) VALUES(6,6,'120.0.0.1',9176,1,'Instance 1',NULL);

INSERT INTO World_1.Registry (ACCOUNT,ID,LOGGED_IN,NAME,ZONE,X,Y,Z,FACING_ANGLE,INSTANCE_ZONE,INSTANCE_X,INSTANCE_Y,INSTANCE_Z,INSTANCE_FACING_ANGLE,HIT_POINTS) VALUES(1,1,0,'Fluffy',0,0,0,0,0,0,0,0,0,0,0);